<?php

use App\Http\Controllers\Authcontroller;
use App\Http\Controllers\comptabiliteController;
use App\Http\Controllers\ctechniqueController;
use App\Http\Controllers\exploatationController;
use App\Http\Controllers\formationController;
use App\Http\Controllers\gestionController;
use App\Http\Controllers\inscriptionController;
use App\Http\Controllers\judiciaireController;
use App\Http\Controllers\mainController;
use App\Http\Controllers\maintenanceController;
use App\Http\Controllers\personelleController;
use App\Http\Controllers\securiteController;
use App\Http\Middleware\CheckEntreprise;
use App\Http\Middleware\CheckUser;
use App\Http\Middleware\rolesMiddleware;
use Illuminate\Support\Facades\Route;


Route::get('/email', function () {
    return redirect()->away('https://webmail.etus22.dz/');
})->name('email');
Route::get('/login', [Authcontroller::class, 'login'])->name('login');
Route::post('/login', [Authcontroller::class, 'dologin']);
Route::delete('/logout', [Authcontroller::class, 'logout'])->name('logout')->middleware('auth');
Route::get('/rate_ctechnique', [ctechniqueController::class, 'rate_ctechnique'])->name('rate_ctechnique');
Route::post('/rate_ctechnique', [ctechniqueController::class, 'add_rate_ctechnique']);

Route::get('/', function () {
    return redirect()->route('login');
})->name('index');

Route::prefix('/app')->controller(mainController::class)->name('app.')->middleware(CheckUser::class)->group(function () {
    Route::get('/', 'main')->name('main');

    Route::prefix('/')->controller(MaintenanceController::class)->name('maintenance.')->group(function () {
        Route::get('maintenance_in', 'maintenance_in')->name('maintenance_in')->middleware('rolesMiddleware:maintenance_in');
        Route::post('maintenance_in', 'insertFichemaintenance');
        Route::get('miantenance_validate', 'miantenance_validate')->name('validate')->middleware('rolesMiddleware:maintenance_validate');
        Route::get('maintenance/refresh_validate', 'refresh_validate')->name('refresh_validate')->middleware('rolesMiddleware:maintenance_validate');
        Route::get('maintenance/refresh_validate_day', 'refresh_validate_day')->name('refresh_validate_day')->middleware('rolesMiddleware:maintenance_validate');
        Route::post('maintenance/validate_day', 'validate_day')->name('validate_day')->middleware('rolesMiddleware:maintenance_validate');
        Route::get('maintenance/check-buses',  'checkBuses')->name('check_buses');
        Route::get('maintenance_show', 'maintnenance_show')->name('maintenance_show')->middleware('rolesMiddleware:maintenance_out');
        Route::post('maintenance/pdf', 'generatePDF')->name('pdf');
        Route::post('maintenance/gasoilepdf', 'generate_gasoile_PDF')->name('gasoilepdf');
        Route::post('maintenance/gasoileexcel', 'generate_gasoile_EXCEL')->name('gasoileexcel');
        Route::post('maintenance/km100pdf', 'generate_km100_PDF')->name('km100pdf');
        Route::post('maintenance/etatnreparatiopdf', 'generate_etat_nreparatiopdf')->name('etatnreparatiopdf');
        Route::post('maintenance/excel', 'generateEXCEL')->name('excel');
        Route::post('maintenance/etatkilometrage', 'generateETATKilometrage')->name('etatkilometrage');
        Route::get('maintenance/refreshfichtable', 'refreshfichtable');
        Route::get('maintenance_fix', 'maintnenance_fix')->name('maintenance_fix')->middleware('rolesMiddleware:maintenance_fix');
        Route::get('maintenance/refreshfixtable', 'refreshfixtable');
        Route::post('maintenance/deletefiche:{id}', 'deletefiche');
        Route::get('editfiche:{id}', 'editfiche')->name('maintenance_edit')->middleware('rolesMiddleware:maintenance_fix');
        Route::post('editfiche:{id}', 'doeditfiche');
        Route::get('maintenance_export', 'login_form')->name('maintenance_export');
        Route::get('maintenance_panne', 'maintenance_panne')->name('maintenance_panne')->middleware('rolesMiddleware:maintenance_panne');
        Route::post('maintenance_panne', 'resoudre_maintenance_panne');
        Route::post('maintenance/ajouter_ndpanne', 'ajouter_ndpanne')->name('ajouter_ndpanne');
        Route::post('maintenance/deletefichepanne:{id}', 'deletefichepanne');
        Route::post('maintenance/deletetraveauxlibre:{id}', 'deletetraveauxlibre');
        Route::post('maintenance/suivibus_pdf', 'generate_suivibus_pdf')->name('suivibus_pdf');
        Route::post('maintenance/suivijournaliere_pdf', 'generate_suivijournaliere_pdf')->name('suivijournaliere_pdf');
        Route::post('maintenance/grandtraveaux_pdf', 'generate_grandtraveaux_pdf')->name('grandtraveaux_pdf');
        Route::post('maintenance/etat_piece_pdf', 'generate_etat_piece_pdf')->name('etat_piece_pdf');
        Route::post('maintenance/etat_piece_sansvidange_pdf', 'generate_etat_piece_sansvidange_pdf')->name('etat_piece_sansvidange_pdf');
        Route::post('maintenance/panneencour_pdf', 'generate_panneencour_pdf')->name('panneencours_pdf');
        Route::post('maintenance/etat_vidange_pdf', 'generate_etat_vidange_pdf')->name('etat_vidange_pdf');
        Route::post('maintenance/fiche_suivie_vidange_pdf', 'generate_fiche_suivie_vidange_pdf')->name('fiche_suivie_vidange_pdf');
        Route::post('maintenance/suividatepanne_pdf', 'generate_suividatepanne_pdf')->name('suividatepanne_pdf');
        Route::post('maintenance/pannerapport_pdf', 'generate_Pannerapport_PDF')->name('panne_pdf');
        Route::get('maintenance_vidange', 'maintenance_vidange')->name('maintenance_vidange')->middleware('rolesMiddleware:maintenance_vidange');
        Route::post('maintenance_vidange', 'ajouter_vidange');
        Route::get('maintenance_jauge', 'maintenance_jauge')->name('maintenance_jauge')->middleware('rolesMiddleware:maintenance_jauge');
        Route::post('maintenance_jauge', 'ajouter_jauge');
        Route::post('maintenance/check_jauge_date', 'check_jauge_date')->name('check_jauge_date');
        Route::post('maintenance/ajouter_jauge_huilemoteur', 'ajouter_jauge_huilemoteur')->name('ajouter_jauge_huilemoteur');
        Route::post('maintenance/ajouter_jauge_glaciole', 'ajouter_jauge_glaciole')->name('ajouter_jauge_glaciole');
        Route::post('maintenance/ajouter_jauge_direction', 'ajouter_jauge_direction')->name('ajouter_jauge_direction');
        Route::post('maintenance/ajouter_jauge_btv', 'ajouter_jauge_btv')->name('ajouter_jauge_btv');
        Route::get('traveaux_libre', 'traveaux_libre')->name('traveaux_libre')->middleware('rolesMiddleware:maintenance_tlibre');
        Route::post('traveaux_libre', 'ajouter_traveaux_libre');
        Route::get('statistiques_miantenance', 'statistiques_maintenance')->name('statistiques')->middleware('rolesMiddleware:statistiques_maintenance');
        Route::get('maintenance/statistiques_data',  'statistiques_data')->name('statistiques_data');
        Route::get('maintenance/extincteurs',  'extincteurs')->name('extincteurs')->middleware('rolesMiddleware:extincteurs_maintenance');
    });
    Route::prefix('/')->controller(gestionController::class)->name('gestion.')->group(function () {
        Route::get('manage_user', 'manage_user')->name('manage_user')->middleware('rolesMiddleware:manage_user');
        Route::get('manage_user/add_user', 'add_user')->name('add_user')->middleware('rolesMiddleware:manage_user');
        Route::post('manage_user/add_user', 'do_add_user');
        Route::post('manage_user/deleteuser:{id}', 'delete_user');
        Route::get('manage_user/edit_user:{id}', 'edit_user')->name('edit_user')->middleware('rolesMiddleware:manage_user');
        Route::post('manage_user/edit_user:{id}', 'do_edit_user');
        Route::get('manage_bus', 'manage_bus')->name('manage_bus')->middleware('rolesMiddleware:manage_bus');
        Route::get('manage_bus/add_bus', 'add_bus')->name('add_bus')->middleware('rolesMiddleware:manage_bus');
        Route::post('manage_bus/add_bus', 'do_add_bus');
        Route::get('manage_bus/edit_bus:{id}', 'edit_bus')->name('edit_bus')->middleware('rolesMiddleware:manage_bus');
        Route::post('manage_bus/edit_bus:{id}', 'do_edit_bus');
        Route::get('manage_ligne', 'manage_ligne')->name('manage_ligne')->middleware('rolesMiddleware:manage_ligne');
        Route::get('manage_ligne/add_ligne', 'add_ligne')->name('add_ligne')->middleware('rolesMiddleware:manage_ligne');
        Route::post('manage_ligne/add_ligne', 'do_add_ligne');
        Route::get('manage_ligne/edit_ligne:{id}', 'edit_ligne')->name('edit_ligne')->middleware('rolesMiddleware:manage_ligne');
        Route::post('manage_ligne/edit_ligne:{id}', 'do_edit_ligne');
        Route::get('manage_panne', 'manage_panne')->name('manage_panne')->middleware('rolesMiddleware:manage_panne');
        Route::get('manage_panne/add_panne', 'add_panne')->name('add_panne')->middleware('rolesMiddleware:manage_panne');
        Route::post('manage_panne/add_panne', 'do_add_panne');
        Route::post('manage_panne/deletepanne:{id}', 'delete_panne');
        Route::get('manage_piece', 'manage_piece')->name('manage_piece')->middleware('rolesMiddleware:manage_piece');
        Route::get('manage_piece/add_piece', 'add_piece')->name('add_piece')->middleware('rolesMiddleware:manage_piece');
        Route::post('manage_piece/add_piece', 'do_add_piece');
        Route::post('manage_piece/deletepiece:{id}', 'delete_piece');
        Route::get('manage_extincteurs', 'manage_extincteurs')->name('manage_extincteurs')->middleware('rolesMiddleware:manage_extincteurs');
        Route::get('manage_extincteurs/add_extincteur', 'add_extincteur')->name('add_extincteur')->middleware('rolesMiddleware:manage_extincteurs');
        Route::post('manage_extincteurs/add_extincteur', 'do_add_extincteur');
        Route::post('manage_extincteurs/recharge_extincteur', 'recharge_extincteur')->name('recharge_extincteur');
        // Route::post('user_in','insertUser');        
    });
    Route::prefix('/')->controller(personelleController::class)->name('personelle.')->group(function () {
        Route::get('personelle_stat', 'personelle_stat')->name('statistiques')->middleware('rolesMiddleware:personelle_stat');
    });
    Route::prefix('/')->controller(comptabiliteController::class)->name('comptabilite.')->group(function () {
        Route::get('comptabilite_stat', 'comptabilite_stat')->name('statistiques')->middleware('rolesMiddleware:comptabilite_stat');
    });
    Route::prefix('/')->controller(exploatationController::class)->name('exploatation.')->group(function () {
        Route::get('exploatation_stat', 'exploatation_stat')->name('statistiques')->middleware('rolesMiddleware:exploatation_stat');
    });
    Route::prefix('/')->controller(judiciaireController::class)->name('judiciaire.')->group(function () {
        Route::get('judiciaire_in', 'judiciaire_in')->name('declare')->middleware('rolesMiddleware:judiciaire_in');
        Route::post('judiciaire_in', 'do_judiciaire_in')->middleware('rolesMiddleware:judiciaire_in');
        Route::post('judiciaire_photos', 'do_judiciaire_photos')->name('ajoute_photos')->middleware('rolesMiddleware:judiciaire_in');
        Route::get('judiciaire_suivre', 'judiciaire_suivre')->name('suivre')->middleware('rolesMiddleware:judiciaire_in');
        Route::post('judiciaire/handle_caat:{id},{date}', 'handle_caat');
        Route::post('judiciaire/handle_paye:{id},{date},{montant}', 'handle_paye');
        Route::get('judiciaire_extraire', 'judiciaire_extraire')->name('extraire')->middleware('rolesMiddleware:judiciaire_out');
        Route::post('judiciaire/etat_accident', 'etat_accident')->name('etat_accident');
        Route::post('judiciaire/naccident_chauffeur', 'etat_naccident_chauffeur')->name('naccident_chauffeur');
        Route::get('judiciaire_commission', 'judiciaire_commission')->name('commission')->middleware('rolesMiddleware:judiciaire_commission');
        Route::post('judiciaire_commission', 'add_judiciaire_commission')->middleware('rolesMiddleware:judiciaire_commission');
        Route::post('judiciaire/commission_word', 'generate_commission_word')->name('commission_word');
    });
    Route::prefix('/')->controller(ctechniqueController::class)->name('ctechnique.')->group(function () {
        Route::get('ctechnique_in', 'ctechnique_in')->name('ctechnique_in')->middleware('rolesMiddleware:ctechnique_in');
        Route::post('ctechnique_in', 'add_ctechnique_in');
        Route::get('ctechnique_clients', 'ctechnique_clients')->name('ctechnique_clients')->middleware('rolesMiddleware:ctechnique_rendezvous');
        Route::post('ctechnique/deleteclient:{id}', 'deleteclient');
        Route::post('ctechnique/sendmessage', 'sendmessage')->name('sendmessage')->middleware('rolesMiddleware:ctechnique_rendezvous');
        Route::post('ctechnique/refreshcontrole', 'refreshcontrole')->name('refreshcontrole')->middleware('rolesMiddleware:ctechnique_rendezvous');
        Route::get('ctechnique_clients/edit_client:{id}', 'edit_client')->name('edit_client')->middleware('rolesMiddleware:ctechnique_in');
        Route::post('ctechnique_clients/edit_client:{id}', 'do_edit_client');
        // Route::post('ctechnique_in','add_ctechnique_in');
        Route::get('evaluations', 'evaluations')->name('evaluations')->middleware('rolesMiddleware:ctechnique_evaluations');
        Route::get('evaluations/refreshcharts',  'refreshCharts');
        Route::post('evaluations/marquercommelue', 'marquercommelue')->name('marquercommelue');
        Route::post('evaluations/evaluations_pdf', 'evaluations_pdf')->name('evaluations_pdf');
        Route::post('evaluations/etatevaluations_pdf', 'etatevaluations_pdf')->name('etatevaluations_pdf');
        Route::post('evaluations/print_evaluation', 'print_evaluation')->name('print_evaluation');
    });
    Route::prefix('/')->controller(securiteController::class)->name('securite.')->group(function () {
        Route::get('securite/extincteurs', 'extincteurs')->name('extincteurs')->middleware('rolesMiddleware:securite_extincteurs');
        Route::post('securite/recharger_extincteur', 'recharger_extincteur')->name('recharger_extincteur');
    });
    Route::prefix('/')->controller(formationController::class)->name('formation.')->group(function () {
        Route::get('formation/taxis_prov', 'confirmer_taxis_prov')->name('confirmer_taxis_prov')->middleware('rolesMiddleware:confirmer_taxis_prov');
        Route::get('formation/taxis', 'confirmer_taxis')->name('confirmer_taxis')->middleware('rolesMiddleware:confirmer_taxis');
        Route::post('formation/rejet_taxi', 'do_rejet_taxis')->name('rejet_taxi')->middleware('rolesMiddleware:confirmer_taxis');
        Route::post('formation/confirmer_taxi', 'do_confirmer_taxis')->name('confirmer_taxi')->middleware('rolesMiddleware:confirmer_taxis');
        Route::post('formation/confirmer_list', 'do_confirmer_list')->name('confirmer_list')->middleware('rolesMiddleware:confirmer_taxis');
        Route::post('formation/print_list', 'print_list_taxis')->name('print_list_taxis')->middleware('rolesMiddleware:confirmer_taxis');
        Route::get('formation/manage_list_taxis', 'manage_list_taxis')->name('manage_list_taxis')->middleware('rolesMiddleware:manage_list_taxis');
        Route::get('formation/create_list_taxis', 'create_list_taxis')->name('create_list')->middleware('rolesMiddleware:manage_list_taxis');
        Route::get('formation/personne', 'transport_personne')->name('transport_personne')->middleware('rolesMiddleware:manage_transpors');
        Route::get('formation/marchandise', 'transport_marchandise')->name('transport_marchandise')->middleware('rolesMiddleware:manage_transpors');
        Route::get('formation/danger', 'transport_danger')->name('transport_danger')->middleware('rolesMiddleware:manage_transpors');
        Route::post('formation/valider', 'valider_transport')->name('valider_transport')->middleware('rolesMiddleware:manage_transpors');
        Route::get('formation/formation_taxi', 'taxis')->name('formation_taxi')->middleware('rolesMiddleware:manage_transpors');
        Route::post('formation/print_attestation', 'print_attestation')->name('print_attestation')->middleware('rolesMiddleware:manage_transpors');
        Route::get('formation/foramtion_sessions', 'foramtion_sessions')->name('foramtion_sessions')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/create_foramtion_sessions', 'do_create_foramtion_sessions')->name('create_foramtion_sessions')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_list_session', 'print_list_session')->name('print_list_session')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/confirm_session', 'confirm_session')->name('confirm_session')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/save-draft',  'save_draft')->name('save_draft')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_detail_session', 'print_detail_session')->name('print_detail_session')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_delibiration', 'print_delibiration')->name('print_delibiration')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_delibiration_fiches', 'print_delibiration_fiches')->name('print_delibiration_fiches')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_notes_paper', 'print_notes_paper')->name('print_notes_paper')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_presence_paper', 'print_presence_paper')->name('print_presence_paper')->middleware('rolesMiddleware:foramtion_sessions');
        Route::post('formation/print_diplomes', 'print_diplomes')->name('print_diplomes')->middleware('rolesMiddleware:foramtion_sessions');
        Route::get('formation/entreprises', 'transport_entreprises')->name('transport_entreprises')->middleware('rolesMiddleware:formation_entreprises');
        Route::post('formation/entrepise_details', 'print_entrepise_details')->name('print_entrepise_details')->middleware('rolesMiddleware:foramtion_sessions');

    });
});
Route::prefix('/inscription')->controller(MaintenanceController::class)->name('inscription.')->group(function () {
    Route::get('/', [inscriptionController::class, 'inscription'])->name('inscription_formation');
    Route::get('/insc_entreprise', [inscriptionController::class, 'insc_entreprise'])->name('inscription_entreprise');
    Route::post('/insc_entreprise', [inscriptionController::class, 'add_entreprise']);
    Route::get('/main_entreprise', [inscriptionController::class, 'main_entreprise'])->middleware(CheckEntreprise::class)->name('main_entreprise');
    Route::post('/add_entreprise_emp', [inscriptionController::class, 'add_entreprise_emp'])->middleware(CheckEntreprise::class)->name('add_entreprise_emp');
    Route::post('/demande_proformat', [inscriptionController::class, 'demande_proformat'])->middleware(CheckEntreprise::class)->name('demande_proformat');
    Route::get('/login_entreprise', [inscriptionController::class, 'login_entreprise'])->name('login_entreprise');
    Route::post('/login_entreprise', [inscriptionController::class, 'do_login_entreprise']);
    Route::get('/insc_taxi', [inscriptionController::class, 'insc_taxi'])->name('inscription_taxi');
    Route::post('/insc_taxi', [inscriptionController::class, 'add_taxi']);
    Route::get('/insc_tper', [inscriptionController::class, 'insc_tper'])->name('inscription_tper');
    Route::post('/insc_tper', [inscriptionController::class, 'add_tper']);
    Route::get('/insc_tmar', [inscriptionController::class, 'insc_tmar'])->name('inscription_tmar');
    Route::post('/insc_tmar', [inscriptionController::class, 'add_tmar']);
    Route::get('/insc_tdan', [inscriptionController::class, 'insc_tdan'])->name('inscription_tdan');
    Route::post('/insc_tdan', [inscriptionController::class, 'add_tdan']);
    Route::get('/success/{type_insc}/{id}', [inscriptionController::class, 'dynamic_success'])->name('success');
    Route::get('/download/{type_insc}/{id}', [inscriptionController::class, 'dynamic_downloadPdf'])->name('download');
});
// Route::post('/inscription', [inscriptionController::class, 'add_rate_ctechnique']);
Route::get('/taxi', [inscriptionController::class, 'taxi_provesoire'])->name('inscription_taxi');
Route::post('/taxi', [inscriptionController::class, 'add_taxi_provesoire']);
Route::get('/taxi/success/{id}', [inscriptionController::class, 'success'])->name('inscription_taxi.success');
Route::get('/taxi/download/{id}', [inscriptionController::class, 'downloadPdf'])->name('inscription_taxi.download');
